name: Jefferson Quispe Pinares
bio: Be more to serve better
description: Full-time Master student Computer Science
external-image: true
picture: assets/images/profile.jpg
resume: true
resume-external: true
resume-url: 'https://cutt.ly/VeixJRo'
resume-pt-url: 'https://cutt.ly/VeixJRo'
lattes-url: null
lattes-pt-url: null
url: jeffersonquispe.github.io
real-url: jeffersonquispe.github.io
permalink: '/:title/'
analytics-google: UA-62025300-1
disqus:
  shortname: JeffersonQuispe
  categories:
    - blog
    - project
facebook: 1343750403
twitter: jefferson_qp
instagram: jeffqp
linkedin: jefferson-quispe-pinares
youtube: channel/UCN8zMoUDtRrEI9ri--yu9eQ
github: jeffersonquispe
medium: jeffersonquispep
email: jeffersonquispep@gmail.com
flickr: photos/148613786@N07
authors:
  jeffersonquispe:
    name: Jefferson Quispe Pinares
    bio: Be more to serve better
    external-image: true
    picture: assets/images/profile.jpg
width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
