name: CITE Textil Camélidos Cusco
bio: El CITE textil camélidos Cusco es un brazo ejecutor del ITP - Instituto Tecnológico de la Producción del Ministerio de la Producción - PRODUCE.
description: El CITE textil camélidos Cusco es un brazo ejecutor del ITP - Instituto Tecnológico de la Producción del Ministerio de la Producción - PRODUCE.
external-image: true
picture: assets/images/profile.jpg
resume: true
resume-external: true
resume-url: "https://cutt.ly/VeixJRo"
resume-pt-url: "https://cutt.ly/VeixJRo"
lattes-url: null
lattes-pt-url: null
url: CITEcusco.github.io
real-url: CITEcusco.github.io
permalink: "/:title/"
#analytics-google: UA-62025300-1
disqus:
  shortname: CITETextil Cusco
  categories:
    - blog
facebook: CITEtextilCamelidosCusco
instagram: citecusco
linkedin: cite-textil-camélidos-cusco-355339200
youtube: UCCSc8Zj0TD3qC2dMTQQRMqw

width: normal
projects: true
about: true
blog: true
sinapsis: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
